export const STAGE_ORDER = [
    "Baby I",
    "Baby II",
    "Child",
    "Adult",
    "Perfect",
    "Ultimate",
];
export const INVENTORY_CONFIG = [
    {
        key: "mushroom",
        activeKey: "mushroom",
        asset: "data/ui/food_mushroom.svg",
        alt: "Mushroom",
        label: "Mushroom (+1 HP)",
    },
    {
        key: "pepper",
        activeKey: "pepper",
        asset: "data/ui/food_pepper.svg",
        alt: "Pepper",
        label: "Pepper (Final Attack)",
    },
    {
        key: "blueApple",
        activeKey: "blue_apple",
        asset: "data/ui/food_blue_apple.svg",
        alt: "Blue Apple",
        label: "Blue Apple (Guaranteed Evolution)",
    },
    {
        key: "medicine",
        activeKey: "medicine",
        asset: "data/ui/food_medicine.svg",
        alt: "Medicine",
        label: "Medicine (Status Immunity)",
    },
    {
        key: "yellowPear",
        activeKey: "yellow_pear",
        asset: "data/ui/food_yellow_pear.svg",
        alt: "Yellow Pear",
        label: "Yellow Pear (+20% Special)",
    },
    {
        key: "stormCloud",
        activeKey: "storm_cloud",
        asset: "data/ui/item_storm_cloud.svg",
        alt: "Storm Cloud",
        label: "Storm Cloud (+10% Paralyze)",
    },
    {
        key: "poisonVial",
        activeKey: "poison_vial",
        asset: "data/ui/item_poison_vial.svg",
        alt: "Poison Vial",
        label: "Poison Vial (+10% Poison)",
    },
    {
        key: "beerBottle",
        activeKey: "beer_bottle",
        asset: "data/ui/item_beer_bottle.svg",
        alt: "Beer Bottle",
        label: "Beer Bottle (+10% Confuse)",
    },
    {
        key: "focusLens",
        activeKey: "focus_lens",
        asset: "data/ui/item_focus_lens.svg",
        alt: "Focus Lens",
        label: "Focus Lens (+25% Special)",
    },
    {
        key: "aegisCharm",
        activeKey: "aegis_charm",
        asset: "data/ui/item_aegis_charm.svg",
        alt: "Aegis Charm",
        label: "Aegis Charm (Blocks First Status)",
    },
    {
        key: "adrenalSeed",
        activeKey: "adrenal_seed",
        asset: "data/ui/item_adrenal_seed.svg",
        alt: "Adrenal Seed",
        label: "Adrenal Seed (1 HP Extra Turn)",
    },
    {
        key: "echoShell",
        activeKey: "echo_shell",
        asset: "data/ui/item_echo_shell.svg",
        alt: "Echo Shell",
        label: "Echo Shell (Repeat Special Hit)",
    },
    {
        key: "nullPowder",
        activeKey: "null_powder",
        asset: "data/ui/item_null_powder.svg",
        alt: "Null Powder",
        label: "Null Powder (Cleanse Battle Start)",
    },
    {
        key: "weightedAnklet",
        activeKey: "weighted_anklet",
        asset: "data/ui/item_weighted_anklet.svg",
        alt: "Weighted Anklet",
        label: "Weighted Anklet (-Enemy Hit, -Self Hit)",
    },
    {
        key: "rationPack",
        activeKey: "ration_pack",
        asset: "data/ui/item_ration_pack.svg",
        alt: "Ration Pack",
        label: "Ration Pack (Auto Training Save)",
    },
    {
        key: "mutationCore",
        activeKey: "mutation_core",
        asset: "data/ui/item_mutation_core.svg",
        alt: "Mutation Core",
        label: "Mutation Core (+Evolution Chance)",
    },
    {
        key: "luckyToken",
        activeKey: "lucky_token",
        asset: "data/ui/item_lucky_token.svg",
        alt: "Lucky Token",
        label: "Lucky Token (Better Drops)",
    },
    {
        key: "lastStandEmblem",
        activeKey: "last_stand_emblem",
        asset: "data/ui/item_last_stand_emblem.svg",
        alt: "Last Stand Emblem",
        label: "Last Stand Emblem (Revive Once)",
    },
];
