function byId(id) {
    const el = document.getElementById(id);
    if (!el) {
        throw new Error(`Missing required element: #${id}`);
    }
    return el;
}
function byQuery(selector) {
    const el = document.querySelector(selector);
    if (!el) {
        throw new Error(`Missing required element: ${selector}`);
    }
    return el;
}
export const singlePlayerButton = byId("single-player");
export const arenaModeButton = byId("arena-mode");
export const exitButton = byId("exit");
export const mainMenu = byId("main-menu");
export const arenaMenu = byId("arena-menu");
export const arenaPlayerList = byId("arena-player-list");
export const arenaOpponentList = byId("arena-opponent-list");
export const arenaStartButton = byId("arena-start");
export const arenaBackButton = byId("arena-back");
export const characterMenu = byId("character-menu");
export const playerList = byId("player-list");
export const startGameButton = byId("start-game");
export const backButton = byId("back");
export const actionMenu = byId("action-menu");
export const actionBackButton = byId("action-back");
export const feedButton = byId("feed");
export const trainButton = byId("train");
export const battleButton = byId("battle");
export const finalChallengeButton = byId("final-challenge");
export const weightCounter = byId("weight-counter");
export const winRateDisplay = byId("win-rate");
export const caretakerSprite = byId("caretaker-sprite");
export const caretakerName = byId("caretaker-name");
export const caretakerStage = byId("caretaker-stage");
export const caretakerHp = byId("caretaker-hp");
export const caretakerTypeIcon = byId("caretaker-type-icon");
export const consumableStatus = byId("consumable-status");
export const trainingCounter = byId("training-counter");
export const feedMenu = byId("feed-menu");
export const feedBackButton = byId("feed-back");
export const feedMeatButton = byId("feed-meat");
export const feedSpriteSlot = byId("feed-sprite");
export const feedFoodSprite = byId("feed-food-img");
export const feedFoodContainer = byQuery(".feed-food");
export const feedMushroomButton = byId("feed-mushroom");
export const mushroomCount = byId("mushroom-count");
export const feedPepperButton = byId("feed-pepper");
export const pepperCount = byId("pepper-count");
export const feedBlueAppleButton = byId("feed-blue-apple");
export const blueAppleCount = byId("blue-apple-count");
export const feedMedicineButton = byId("feed-medicine");
export const medicineCount = byId("medicine-count");
export const feedYellowPearButton = byId("feed-yellow-pear");
export const yellowPearCount = byId("yellow-pear-count");
export const feedStormCloudButton = byId("feed-storm-cloud");
export const stormCloudCount = byId("storm-cloud-count");
export const feedPoisonVialButton = byId("feed-poison-vial");
export const poisonVialCount = byId("poison-vial-count");
export const feedBeerBottleButton = byId("feed-beer-bottle");
export const beerBottleCount = byId("beer-bottle-count");
export const feedFocusLensButton = byId("feed-focus-lens");
export const focusLensCount = byId("focus-lens-count");
export const feedAegisCharmButton = byId("feed-aegis-charm");
export const aegisCharmCount = byId("aegis-charm-count");
export const feedAdrenalSeedButton = byId("feed-adrenal-seed");
export const adrenalSeedCount = byId("adrenal-seed-count");
export const feedEchoShellButton = byId("feed-echo-shell");
export const echoShellCount = byId("echo-shell-count");
export const feedNullPowderButton = byId("feed-null-powder");
export const nullPowderCount = byId("null-powder-count");
export const feedWeightedAnkletButton = byId("feed-weighted-anklet");
export const weightedAnkletCount = byId("weighted-anklet-count");
export const feedRationPackButton = byId("feed-ration-pack");
export const rationPackCount = byId("ration-pack-count");
export const feedMutationCoreButton = byId("feed-mutation-core");
export const mutationCoreCount = byId("mutation-core-count");
export const feedLuckyTokenButton = byId("feed-lucky-token");
export const luckyTokenCount = byId("lucky-token-count");
export const feedLastStandEmblemButton = byId("feed-last-stand-emblem");
export const lastStandEmblemCount = byId("last-stand-emblem-count");
export const trainMenu = byId("train-menu");
export const trainBackButton = byId("train-back");
export const trainFill = byId("train-fill");
export const trainStatus = byId("train-status");
export const trainRetryButton = byId("train-retry");
export const trainSpriteSlot = byId("train-sprite");
export const trainBag = byId("train-bag");
export const evolutionScreen = byId("evolution-screen");
export const evolutionOld = byId("evolution-old");
export const evolutionNew = byId("evolution-new");
export const evolutionMessage = byId("evolution-message");
export const evolutionContinue = byId("evolution-continue");
export const gameoverScreen = byId("gameover-screen");
export const gameoverSprite = byId("gameover-sprite");
export const gameoverContinue = byId("gameover-continue");
export const congratsScreen = byId("congrats-screen");
export const congratsSprite = byId("congrats-sprite");
export const congratsContinue = byId("congrats-continue");
export const battleScreen = byId("battle-screen");
export const battleBackButton = byId("battle-back");
export const finalChallengeModal = byId("final-challenge-modal");
export const finalChallengeConfirmButton = byId("final-challenge-confirm");
export const finalChallengeCancelButton = byId("final-challenge-cancel");
export const actionBackModal = byId("action-back-modal");
export const actionBackConfirmButton = byId("action-back-confirm");
export const actionBackCancelButton = byId("action-back-cancel");
export const battlePlayerName = byId("battle-player-name");
export const battleOpponentName = byId("battle-opponent-name");
export const battlePlayerHp = byId("battle-player-hp");
export const battleOpponentHp = byId("battle-opponent-hp");
export const battleLog = byId("battle-log");
export const battlePlayerSprite = byId("battle-player-sprite");
export const battleOpponentSprite = byId("battle-opponent-sprite");
export const battleField = byId("battle-field");
export const playerStatusParalyzed = byId("player-status-paralyzed");
export const playerStatusPoisoned = byId("player-status-poisoned");
export const playerStatusConfused = byId("player-status-confused");
export const opponentStatusParalyzed = byId("opponent-status-paralyzed");
export const opponentStatusPoisoned = byId("opponent-status-poisoned");
export const opponentStatusConfused = byId("opponent-status-confused");
