function byId<T extends HTMLElement>(id: string): T {
  const el = document.getElementById(id);
  if (!el) {
    throw new Error(`Missing required element: #${id}`);
  }
  return el as T;
}

function byQuery<T extends Element>(selector: string): T {
  const el = document.querySelector(selector);
  if (!el) {
    throw new Error(`Missing required element: ${selector}`);
  }
  return el as T;
}

export const singlePlayerButton = byId<HTMLButtonElement>("single-player");
export const arenaModeButton = byId<HTMLButtonElement>("arena-mode");
export const exitButton = byId<HTMLButtonElement>("exit");
export const mainMenu = byId<HTMLElement>("main-menu");
export const arenaMenu = byId<HTMLElement>("arena-menu");
export const arenaPlayerList = byId<HTMLElement>("arena-player-list");
export const arenaOpponentList = byId<HTMLElement>("arena-opponent-list");
export const arenaStartButton = byId<HTMLButtonElement>("arena-start");
export const arenaBackButton = byId<HTMLButtonElement>("arena-back");
export const characterMenu = byId<HTMLElement>("character-menu");
export const playerList = byId<HTMLElement>("player-list");
export const startGameButton = byId<HTMLButtonElement>("start-game");
export const backButton = byId<HTMLButtonElement>("back");
export const actionMenu = byId<HTMLElement>("action-menu");
export const actionBackButton = byId<HTMLButtonElement>("action-back");
export const feedButton = byId<HTMLButtonElement>("feed");
export const trainButton = byId<HTMLButtonElement>("train");
export const battleButton = byId<HTMLButtonElement>("battle");
export const finalChallengeButton = byId<HTMLButtonElement>("final-challenge");
export const weightCounter = byId<HTMLElement>("weight-counter");
export const winRateDisplay = byId<HTMLElement>("win-rate");
export const caretakerSprite = byId<HTMLElement>("caretaker-sprite");
export const caretakerName = byId<HTMLElement>("caretaker-name");
export const caretakerStage = byId<HTMLElement>("caretaker-stage");
export const caretakerHp = byId<HTMLElement>("caretaker-hp");
export const caretakerTypeIcon = byId<HTMLImageElement>("caretaker-type-icon");
export const consumableStatus = byId<HTMLElement>("consumable-status");
export const trainingCounter = byId<HTMLElement>("training-counter");
export const feedMenu = byId<HTMLElement>("feed-menu");
export const feedBackButton = byId<HTMLButtonElement>("feed-back");
export const feedMeatButton = byId<HTMLButtonElement>("feed-meat");
export const feedSpriteSlot = byId<HTMLElement>("feed-sprite");
export const feedFoodSprite = byId<HTMLImageElement>("feed-food-img");
export const feedFoodContainer = byQuery<HTMLElement>(".feed-food");
export const feedMushroomButton = byId<HTMLButtonElement>("feed-mushroom");
export const mushroomCount = byId<HTMLElement>("mushroom-count");
export const feedPepperButton = byId<HTMLButtonElement>("feed-pepper");
export const pepperCount = byId<HTMLElement>("pepper-count");
export const feedBlueAppleButton = byId<HTMLButtonElement>("feed-blue-apple");
export const blueAppleCount = byId<HTMLElement>("blue-apple-count");
export const feedMedicineButton = byId<HTMLButtonElement>("feed-medicine");
export const medicineCount = byId<HTMLElement>("medicine-count");
export const feedYellowPearButton = byId<HTMLButtonElement>("feed-yellow-pear");
export const yellowPearCount = byId<HTMLElement>("yellow-pear-count");
export const feedStormCloudButton = byId<HTMLButtonElement>("feed-storm-cloud");
export const stormCloudCount = byId<HTMLElement>("storm-cloud-count");
export const feedPoisonVialButton = byId<HTMLButtonElement>("feed-poison-vial");
export const poisonVialCount = byId<HTMLElement>("poison-vial-count");
export const feedBeerBottleButton = byId<HTMLButtonElement>("feed-beer-bottle");
export const beerBottleCount = byId<HTMLElement>("beer-bottle-count");
export const feedFocusLensButton = byId<HTMLButtonElement>("feed-focus-lens");
export const focusLensCount = byId<HTMLElement>("focus-lens-count");
export const feedAegisCharmButton = byId<HTMLButtonElement>("feed-aegis-charm");
export const aegisCharmCount = byId<HTMLElement>("aegis-charm-count");
export const feedAdrenalSeedButton = byId<HTMLButtonElement>("feed-adrenal-seed");
export const adrenalSeedCount = byId<HTMLElement>("adrenal-seed-count");
export const feedEchoShellButton = byId<HTMLButtonElement>("feed-echo-shell");
export const echoShellCount = byId<HTMLElement>("echo-shell-count");
export const feedNullPowderButton = byId<HTMLButtonElement>("feed-null-powder");
export const nullPowderCount = byId<HTMLElement>("null-powder-count");
export const feedWeightedAnkletButton = byId<HTMLButtonElement>("feed-weighted-anklet");
export const weightedAnkletCount = byId<HTMLElement>("weighted-anklet-count");
export const feedRationPackButton = byId<HTMLButtonElement>("feed-ration-pack");
export const rationPackCount = byId<HTMLElement>("ration-pack-count");
export const feedMutationCoreButton = byId<HTMLButtonElement>("feed-mutation-core");
export const mutationCoreCount = byId<HTMLElement>("mutation-core-count");
export const feedLuckyTokenButton = byId<HTMLButtonElement>("feed-lucky-token");
export const luckyTokenCount = byId<HTMLElement>("lucky-token-count");
export const feedLastStandEmblemButton = byId<HTMLButtonElement>("feed-last-stand-emblem");
export const lastStandEmblemCount = byId<HTMLElement>("last-stand-emblem-count");
export const trainMenu = byId<HTMLElement>("train-menu");
export const trainBackButton = byId<HTMLButtonElement>("train-back");
export const trainFill = byId<HTMLElement>("train-fill");
export const trainStatus = byId<HTMLElement>("train-status");
export const trainRetryButton = byId<HTMLButtonElement>("train-retry");
export const trainSpriteSlot = byId<HTMLElement>("train-sprite");
export const trainBag = byId<HTMLElement>("train-bag");
export const evolutionScreen = byId<HTMLElement>("evolution-screen");
export const evolutionOld = byId<HTMLElement>("evolution-old");
export const evolutionNew = byId<HTMLElement>("evolution-new");
export const evolutionMessage = byId<HTMLElement>("evolution-message");
export const evolutionContinue = byId<HTMLButtonElement>("evolution-continue");
export const gameoverScreen = byId<HTMLElement>("gameover-screen");
export const gameoverSprite = byId<HTMLElement>("gameover-sprite");
export const gameoverContinue = byId<HTMLButtonElement>("gameover-continue");
export const congratsScreen = byId<HTMLElement>("congrats-screen");
export const congratsSprite = byId<HTMLElement>("congrats-sprite");
export const congratsContinue = byId<HTMLButtonElement>("congrats-continue");
export const battleScreen = byId<HTMLElement>("battle-screen");
export const battleBackButton = byId<HTMLButtonElement>("battle-back");
export const finalChallengeModal = byId<HTMLElement>("final-challenge-modal");
export const finalChallengeConfirmButton = byId<HTMLButtonElement>("final-challenge-confirm");
export const finalChallengeCancelButton = byId<HTMLButtonElement>("final-challenge-cancel");
export const actionBackModal = byId<HTMLElement>("action-back-modal");
export const actionBackConfirmButton = byId<HTMLButtonElement>("action-back-confirm");
export const actionBackCancelButton = byId<HTMLButtonElement>("action-back-cancel");
export const battlePlayerName = byId<HTMLElement>("battle-player-name");
export const battleOpponentName = byId<HTMLElement>("battle-opponent-name");
export const battlePlayerHp = byId<HTMLElement>("battle-player-hp");
export const battleOpponentHp = byId<HTMLElement>("battle-opponent-hp");
export const battleLog = byId<HTMLElement>("battle-log");
export const battlePlayerSprite = byId<HTMLElement>("battle-player-sprite");
export const battleOpponentSprite = byId<HTMLElement>("battle-opponent-sprite");
export const battleField = byId<HTMLElement>("battle-field");
export const playerStatusParalyzed = byId<HTMLImageElement>("player-status-paralyzed");
export const playerStatusPoisoned = byId<HTMLImageElement>("player-status-poisoned");
export const playerStatusConfused = byId<HTMLImageElement>("player-status-confused");
export const opponentStatusParalyzed = byId<HTMLImageElement>("opponent-status-paralyzed");
export const opponentStatusPoisoned = byId<HTMLImageElement>("opponent-status-poisoned");
export const opponentStatusConfused = byId<HTMLImageElement>("opponent-status-confused");
